/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include "axil_pib_dma_reg_types.h"

void	setAxilPibDmaIrqCtrl(
	bool *		enable
);

void	setAxilPibDmaAck(
	bool *		error,
	bool *		irq
);

void	getAxilPibDmaStatus(
	bool *		unsupported_op,
	bool *		write_error,
	bool *		read_error,
	DMAState *	state
);

void	setAxilPibDmaSource(
	uint32_t *	pointer
);

void	setAxilPibDmaLength(
	uint32_t *	bytes
);

void	setAxilPibDmaDestination(
	uint32_t *	pointer
);

void	setAxilPibDmaControl(
	DMAOpCode *	op
);

void	setAxilPibDmaSet(
	uint32_t *	val
);
