/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

#include "axil_pib_dma_regs.h"

void
setAxilPibDmaIrqCtrl(
	bool *		enable)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*enable & 0x1) << 0;

	*(volatile uint32_t *)(0x2000000) = reg_val;
}

void
setAxilPibDmaAck(
	bool *		error,
	bool *		irq)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*error & 0x1) << 0;
	reg_val |= ((uint32_t)*irq & 0x1) << 8;

	*(volatile uint32_t *)(0x2000004) = reg_val;
}

void
getAxilPibDmaStatus(
	bool *		unsupported_op,
	bool *		write_error,
	bool *		read_error,
	DMAState *	state)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x2000008);
	*unsupported_op= (bool)((reg_val >> 0) & 0x1);
	*write_error= (bool)((reg_val >> 8) & 0x1);
	*read_error= (bool)((reg_val >> 16) & 0x1);
	*state= (DMAState)((reg_val >> 24) & 0x3);
}

void
setAxilPibDmaSource(
	uint32_t *	pointer)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*pointer & 0xffffffff) << 0;

	*(volatile uint32_t *)(0x200000c) = reg_val;
}

void
setAxilPibDmaLength(
	uint32_t *	bytes)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*bytes & 0xffffffff) << 0;

	*(volatile uint32_t *)(0x2000010) = reg_val;
}

void
setAxilPibDmaDestination(
	uint32_t *	pointer)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*pointer & 0xffffffff) << 0;

	*(volatile uint32_t *)(0x2000014) = reg_val;
}

void
setAxilPibDmaControl(
	DMAOpCode *	op)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*op & 0xff) << 0;

	*(volatile uint32_t *)(0x2000018) = reg_val;
}

void
setAxilPibDmaSet(
	uint32_t *	val)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*val & 0xffffffff) << 0;

	*(volatile uint32_t *)(0x200001c) = reg_val;
}
