/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

#include "csr_pack_unpack.h"

void
unpackCsrCommand(
	uint32_t *	registerValue,
	uint32_t *	command)
{
	uint32_t reg_val = *registerValue;
	*command= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
packCsrCommand(
	uint32_t *	registerValue,
	uint32_t *	command)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*command & 0xffffffff) << 0;

	*registerValue = reg_val;
}

void
unpackCsrConfig(
	uint32_t *	registerValue,
	bool *		rstn,
	bool *		unlock_bitstream_section,
	bool *		sw_led_enable,
	bool *		sw_led,
	bool *		green_led,
	bool *		debug_pin_0,
	uint32_t *	reserved)
{
	uint32_t reg_val = *registerValue;
	*rstn= (bool)((reg_val >> 0) & 0x1);
	*unlock_bitstream_section= (bool)((reg_val >> 1) & 0x1);
	*sw_led_enable= (bool)((reg_val >> 2) & 0x1);
	*sw_led= (bool)((reg_val >> 3) & 0x1);
	*green_led= (bool)((reg_val >> 4) & 0x1);
	*debug_pin_0= (bool)((reg_val >> 5) & 0x1);
	*reserved= (uint32_t)((reg_val >> 6) & 0x3ffffff);
}
void
packCsrConfig(
	uint32_t *	registerValue,
	bool *		rstn,
	bool *		unlock_bitstream_section,
	bool *		sw_led_enable,
	bool *		sw_led,
	bool *		green_led,
	bool *		debug_pin_0,
	uint32_t *	reserved)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*rstn & 0x1) << 0;
	reg_val |= ((uint32_t)*unlock_bitstream_section & 0x1) << 1;
	reg_val |= ((uint32_t)*sw_led_enable & 0x1) << 2;
	reg_val |= ((uint32_t)*sw_led & 0x1) << 3;
	reg_val |= ((uint32_t)*green_led & 0x1) << 4;
	reg_val |= ((uint32_t)*debug_pin_0 & 0x1) << 5;
	reg_val |= ((uint32_t)*reserved & 0x3ffffff) << 6;

	*registerValue = reg_val;
}

void
unpackCsrStatus(
	uint32_t *	registerValue,
	uint32_t *	status)
{
	uint32_t reg_val = *registerValue;
	*status= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
packCsrStatus(
	uint32_t *	registerValue,
	uint32_t *	status)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*status & 0xffffffff) << 0;

	*registerValue = reg_val;
}

void
unpackCsrSdConfig(
	uint32_t *	registerValue,
	bool *		force_write_crc_ok,
	uint8_t *	reserved_0,
	bool *		ignore_write_crc_error,
	uint8_t *	reserved_1,
	bool *		connect_crc_error_to_interrupt,
	uint8_t *	reserved_2,
	bool *		crc_error,
	uint8_t *	reserved_3)
{
	uint32_t reg_val = *registerValue;
	*force_write_crc_ok= (bool)((reg_val >> 0) & 0x1);
	*reserved_0= (uint8_t)((reg_val >> 1) & 0x7f);
	*ignore_write_crc_error= (bool)((reg_val >> 8) & 0x1);
	*reserved_1= (uint8_t)((reg_val >> 9) & 0x7f);
	*connect_crc_error_to_interrupt= (bool)((reg_val >> 16) & 0x1);
	*reserved_2= (uint8_t)((reg_val >> 17) & 0x7f);
	*crc_error= (bool)((reg_val >> 24) & 0x1);
	*reserved_3= (uint8_t)((reg_val >> 25) & 0x7f);
}
void
packCsrSdConfig(
	uint32_t *	registerValue,
	bool *		force_write_crc_ok,
	uint8_t *	reserved_0,
	bool *		ignore_write_crc_error,
	uint8_t *	reserved_1,
	bool *		connect_crc_error_to_interrupt,
	uint8_t *	reserved_2,
	bool *		crc_error,
	uint8_t *	reserved_3)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*force_write_crc_ok & 0x1) << 0;
	reg_val |= ((uint32_t)*reserved_0 & 0x7f) << 1;
	reg_val |= ((uint32_t)*ignore_write_crc_error & 0x1) << 8;
	reg_val |= ((uint32_t)*reserved_1 & 0x7f) << 9;
	reg_val |= ((uint32_t)*connect_crc_error_to_interrupt & 0x1) << 16;
	reg_val |= ((uint32_t)*reserved_2 & 0x7f) << 17;
	reg_val |= ((uint32_t)*crc_error & 0x1) << 24;
	reg_val |= ((uint32_t)*reserved_3 & 0x7f) << 25;

	*registerValue = reg_val;
}

void
unpackCsrTrapMcause(
	uint32_t *	registerValue,
	uint32_t *	trap_mcause)
{
	uint32_t reg_val = *registerValue;
	*trap_mcause= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
packCsrTrapMcause(
	uint32_t *	registerValue,
	uint32_t *	trap_mcause)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*trap_mcause & 0xffffffff) << 0;

	*registerValue = reg_val;
}

void
unpackCsrTrapMepc(
	uint32_t *	registerValue,
	uint32_t *	trap_mepc)
{
	uint32_t reg_val = *registerValue;
	*trap_mepc= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
packCsrTrapMepc(
	uint32_t *	registerValue,
	uint32_t *	trap_mepc)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*trap_mepc & 0xffffffff) << 0;

	*registerValue = reg_val;
}

void
unpackCsrTrapMtval(
	uint32_t *	registerValue,
	uint32_t *	trap_mtval)
{
	uint32_t reg_val = *registerValue;
	*trap_mtval= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
packCsrTrapMtval(
	uint32_t *	registerValue,
	uint32_t *	trap_mtval)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*trap_mtval & 0xffffffff) << 0;

	*registerValue = reg_val;
}
