/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

#include "csr_regs.h"

void
getCsrCommand(
	uint32_t *	command)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x10000000);
	*command= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
setCsrCommand(
	uint32_t *	command)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*command & 0xffffffff) << 0;

	*(volatile uint32_t *)(0x10000000) = reg_val;
}

void
getCsrConfig(
	bool *		rstn,
	bool *		sw_led_enable,
	bool *		sw_led,
	bool *		green_led,
	bool *		debug_pin_0)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x10004000);
	*rstn= (bool)((reg_val >> 0) & 0x1);
	*sw_led_enable= (bool)((reg_val >> 2) & 0x1);
	*sw_led= (bool)((reg_val >> 3) & 0x1);
	*green_led= (bool)((reg_val >> 4) & 0x1);
	*debug_pin_0= (bool)((reg_val >> 5) & 0x1);
}
void
setCsrConfig(
	bool *		rstn,
	bool *		sw_led_enable,
	bool *		sw_led,
	bool *		green_led,
	bool *		debug_pin_0)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*rstn & 0x1) << 0;
	reg_val |= ((uint32_t)*sw_led_enable & 0x1) << 2;
	reg_val |= ((uint32_t)*sw_led & 0x1) << 3;
	reg_val |= ((uint32_t)*green_led & 0x1) << 4;
	reg_val |= ((uint32_t)*debug_pin_0 & 0x1) << 5;

	*(volatile uint32_t *)(0x10004000) = reg_val;
}

void
getCsrStatus(
	uint32_t *	status)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x10008000);
	*status= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
setCsrStatus(
	uint32_t *	status)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*status & 0xffffffff) << 0;

	*(volatile uint32_t *)(0x10008000) = reg_val;
}

void
getCsrSdConfig(
	bool *		force_write_crc_ok,
	uint8_t *	reserved_0,
	bool *		ignore_write_crc_error,
	uint8_t *	reserved_1,
	bool *		connect_crc_error_to_interrupt,
	uint8_t *	reserved_2,
	bool *		crc_error,
	uint8_t *	reserved_3)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x1000c000);
	*force_write_crc_ok= (bool)((reg_val >> 0) & 0x1);
	*reserved_0= (uint8_t)((reg_val >> 1) & 0x7f);
	*ignore_write_crc_error= (bool)((reg_val >> 8) & 0x1);
	*reserved_1= (uint8_t)((reg_val >> 9) & 0x7f);
	*connect_crc_error_to_interrupt= (bool)((reg_val >> 16) & 0x1);
	*reserved_2= (uint8_t)((reg_val >> 17) & 0x7f);
	*crc_error= (bool)((reg_val >> 24) & 0x1);
	*reserved_3= (uint8_t)((reg_val >> 25) & 0x7f);
}
void
setCsrSdConfig(
	bool *		force_write_crc_ok,
	uint8_t *	reserved_0,
	bool *		ignore_write_crc_error,
	uint8_t *	reserved_1,
	bool *		connect_crc_error_to_interrupt,
	uint8_t *	reserved_2,
	bool *		crc_error,
	uint8_t *	reserved_3)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*force_write_crc_ok & 0x1) << 0;
	reg_val |= ((uint32_t)*reserved_0 & 0x7f) << 1;
	reg_val |= ((uint32_t)*ignore_write_crc_error & 0x1) << 8;
	reg_val |= ((uint32_t)*reserved_1 & 0x7f) << 9;
	reg_val |= ((uint32_t)*connect_crc_error_to_interrupt & 0x1) << 16;
	reg_val |= ((uint32_t)*reserved_2 & 0x7f) << 17;
	reg_val |= ((uint32_t)*crc_error & 0x1) << 24;
	reg_val |= ((uint32_t)*reserved_3 & 0x7f) << 25;

	*(volatile uint32_t *)(0x1000c000) = reg_val;
}

void
getCsrTrapMcause(
	uint32_t *	trap_mcause)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x10010000);
	*trap_mcause= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
setCsrTrapMcause(
	uint32_t *	trap_mcause)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*trap_mcause & 0xffffffff) << 0;

	*(volatile uint32_t *)(0x10010000) = reg_val;
}

void
getCsrTrapMepc(
	uint32_t *	trap_mepc)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x10010004);
	*trap_mepc= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
setCsrTrapMepc(
	uint32_t *	trap_mepc)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*trap_mepc & 0xffffffff) << 0;

	*(volatile uint32_t *)(0x10010004) = reg_val;
}

void
getCsrTrapMtval(
	uint32_t *	trap_mtval)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x10010008);
	*trap_mtval= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
setCsrTrapMtval(
	uint32_t *	trap_mtval)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*trap_mtval & 0xffffffff) << 0;

	*(volatile uint32_t *)(0x10010008) = reg_val;
}

void
getCsrBitstreamUnlock(
	uint32_t *	key)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x10014000);
	*key= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
setCsrBitstreamUnlock(
	uint32_t *	key)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*key & 0xffffffff) << 0;

	*(volatile uint32_t *)(0x10014000) = reg_val;
}
