/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#pragma once

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

void	getCsrCommand(
	uint32_t *	command
);
void	setCsrCommand(
	uint32_t *	command
);

void	getCsrConfig(
	bool *		rstn,
	bool *		sw_led_enable,
	bool *		sw_led,
	bool *		green_led,
	bool *		debug_pin_0
);
void	setCsrConfig(
	bool *		rstn,
	bool *		sw_led_enable,
	bool *		sw_led,
	bool *		green_led,
	bool *		debug_pin_0
);

void	getCsrStatus(
	uint32_t *	status
);
void	setCsrStatus(
	uint32_t *	status
);

void	getCsrSdConfig(
	bool *		force_write_crc_ok,
	uint8_t *	reserved_0,
	bool *		ignore_write_crc_error,
	uint8_t *	reserved_1,
	bool *		connect_crc_error_to_interrupt,
	uint8_t *	reserved_2,
	bool *		crc_error,
	uint8_t *	reserved_3
);
void	setCsrSdConfig(
	bool *		force_write_crc_ok,
	uint8_t *	reserved_0,
	bool *		ignore_write_crc_error,
	uint8_t *	reserved_1,
	bool *		connect_crc_error_to_interrupt,
	uint8_t *	reserved_2,
	bool *		crc_error,
	uint8_t *	reserved_3
);

void	getCsrTrapMcause(
	uint32_t *	trap_mcause
);
void	setCsrTrapMcause(
	uint32_t *	trap_mcause
);

void	getCsrTrapMepc(
	uint32_t *	trap_mepc
);
void	setCsrTrapMepc(
	uint32_t *	trap_mepc
);

void	getCsrTrapMtval(
	uint32_t *	trap_mtval
);
void	setCsrTrapMtval(
	uint32_t *	trap_mtval
);

void	getCsrBitstreamUnlock(
	uint32_t *	key
);
void	setCsrBitstreamUnlock(
	uint32_t *	key
);
