/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#define TopLramTopEntry 0x106fffc
#define TopLramBottomEntry 0x1000000
#define TopIoBuffTopEntry 0x120fffc
#define TopIoBuffBottomEntry 0x1200000

/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#define SpiFlashBitstreamTopEntry 0x1ffffc
#define SpiFlashBitstreamBottomEntry 0x0
#define SpiFlashUserDataTopEntry 0xfffffc
#define SpiFlashUserDataBottomEntry 0x200000

/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

