/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#define TopFlashOtpTopEntry 0x40002fc
#define TopFlashOtpBottomEntry 0x4000000
#define TopLramTopEntry 0x606fffc
#define TopLramBottomEntry 0x6000000
#define TopPsramTopEntry 0xffffffc
#define TopPsramBottomEntry 0x8000000
#define TopIoBuffTopEntry 0x1010fffc
#define TopIoBuffBottomEntry 0x10100000

/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#define SpiFlashBitstreamTopEntry 0x1ffffc
#define SpiFlashBitstreamBottomEntry 0x0
#define SpiFlashUserDataTopEntry 0x3fffffc
#define SpiFlashUserDataBottomEntry 0x200000

/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

