/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

#include "spi_flash_regs.h"


uint32_t
getSpiFlashBitstreamEntry(uint32_t offset)
{
	return *(volatile uint32_t *)(0x0 + offset);
}

void
setSpiFlashBitstreamEntry(uint32_t offset, uint32_t *  value)
{
	*(volatile uint32_t *)(0x0 + offset) = *value;
}


uint32_t
getSpiFlashUserDataEntry(uint32_t offset)
{
	return *(volatile uint32_t *)(0x200000 + offset);
}

void
setSpiFlashUserDataEntry(uint32_t offset, uint32_t *  value)
{
	*(volatile uint32_t *)(0x200000 + offset) = *value;
}
