/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

#include "top_regs.h"



uint32_t
getTopFlashOtpEntry(uint32_t offset)
{
	return *(volatile uint32_t *)(0x4000000 + offset);
}

void
setTopFlashOtpEntry(uint32_t offset, uint32_t *  value)
{
	*(volatile uint32_t *)(0x4000000 + offset) = *value;
}


uint32_t
getTopLramEntry(uint32_t offset)
{
	return *(volatile uint32_t *)(0x6000000 + offset);
}

void
setTopLramEntry(uint32_t offset, uint32_t *  value)
{
	*(volatile uint32_t *)(0x6000000 + offset) = *value;
}


uint32_t
getTopPsramEntry(uint32_t offset)
{
	return *(volatile uint32_t *)(0x8000000 + offset);
}

void
setTopPsramEntry(uint32_t offset, uint32_t *  value)
{
	*(volatile uint32_t *)(0x8000000 + offset) = *value;
}



uint32_t
getTopIoBuffEntry(uint32_t offset)
{
	return *(volatile uint32_t *)(0x10100000 + offset);
}

void
setTopIoBuffEntry(uint32_t offset, uint32_t *  value)
{
	*(volatile uint32_t *)(0x10100000 + offset) = *value;
}

