/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#pragma once

#include <stdint.h>
#include <stdbool.h>



uint32_t	getTopLramEntry(uint32_t offset);

void	setTopLramEntry(uint32_t offset, uint32_t *  value);



uint32_t	getTopIoBuffEntry(uint32_t offset);

void	setTopIoBuffEntry(uint32_t offset, uint32_t *  value);

