/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#pragma once

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>



uint32_t	getTopFlashOtpEntry(size_t offset);

void	setTopFlashOtpEntry(size_t offset, uint32_t *  value);


uint32_t	getTopLramEntry(size_t offset);

void	setTopLramEntry(size_t offset, uint32_t *  value);


uint32_t	getTopPsramEntry(size_t offset);

void	setTopPsramEntry(size_t offset, uint32_t *  value);



uint32_t	getTopIoBuffEntry(size_t offset);

void	setTopIoBuffEntry(size_t offset, uint32_t *  value);

