/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

#include "top_regs.h"



uint32_t
getTopFlashOtpEntry(size_t offset)
{
	return *(volatile uint32_t *)(0x4000000 + offset);
}

void
setTopFlashOtpEntry(size_t offset, uint32_t *  value)
{
	*(volatile uint32_t *)(0x4000000 + offset) = *value;
}


uint32_t
getTopLramEntry(size_t offset)
{
	return *(volatile uint32_t *)(0x6000000 + offset);
}

void
setTopLramEntry(size_t offset, uint32_t *  value)
{
	*(volatile uint32_t *)(0x6000000 + offset) = *value;
}


uint32_t
getTopPsramEntry(size_t offset)
{
	return *(volatile uint32_t *)(0x8000000 + offset);
}

void
setTopPsramEntry(size_t offset, uint32_t *  value)
{
	*(volatile uint32_t *)(0x8000000 + offset) = *value;
}



uint32_t
getTopIoBuffEntry(size_t offset)
{
	return *(volatile uint32_t *)(0x10100000 + offset);
}

void
setTopIoBuffEntry(size_t offset, uint32_t *  value)
{
	*(volatile uint32_t *)(0x10100000 + offset) = *value;
}

