[project]
name = "signaloid-utilities"
dynamic = ["version"]
description = ""
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Signaloid", email = "info@signaloid.com"}]
dependencies = [
	"requests (>=2.33,<3.0.0)",
	"urllib3 (>=2.7.0,<3)",
]

[project.urls]
homepage = "https://signaloid.com/"
repository = "https://github.com/signaloid/Signaloid-Compute-Module-Utilities"
documentation = "https://docs.signaloid.io"

[project.scripts]
C0-microSD-toolkit = 'signaloid_utilities.c0microsd.toolkit:main'
C0-SD-toolkit = 'signaloid_utilities.c0sd.toolkit:main'
SDDev-toolkit = 'signaloid_utilities.sddev.toolkit:main'
SDDev-power-measure = 'signaloid_utilities.sddev.power_measure:main'
C0-debug-logger = 'signaloid_utilities.debug_logger:main'


[tool.poetry]
requires-poetry = ">=2.0"
packages = [
	{ include = "signaloid_utilities", from = "src/python" },
]
version = "0.0.0"


[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"


[tool.poetry.group.dev.dependencies]
mypy = "^1.19.1"
flake8 = "^7.3.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"


[tool.mypy]
warn_unused_configs = true
strict = true

[[tool.mypy.overrides]]
module = [
	"signaloid_utilities.c0microsd.*",
	"signaloid_utilities.c0sd.*",
	"signaloid_utilities.sddev.*",
	"signaloid_utilities.signaloid_api.*",
]
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
warn_unused_ignores = false
check_untyped_defs = false
strict_equality = false
