# Auto-generated by regmapper - DO NOT MODIFY



class Csr:
    BASE_ADDR = 0x1100000
    class Command:
        ADDR = 0x1100000
        class Command:
            LSB = 0
            MSB = 31
            MASK = 0xffffffff

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_command = (reg_val >> 0) & 0xffffffff
            return f_command


        @staticmethod
        def pack(f_command: int) -> int:
            reg_val = 0
            reg_val |= (f_command & 0xffffffff) << 0
            return reg_val
    class Config:
        ADDR = 0x1104000
        class Rstn:
            LSB = 0
            MSB = 0
            MASK = 0x1
        class UnlockBitstreamSection:
            LSB = 1
            MSB = 1
            MASK = 0x1
        class SwLedEnable:
            LSB = 2
            MSB = 2
            MASK = 0x1
        class SwLed:
            LSB = 3
            MSB = 3
            MASK = 0x1
        class RedLed:
            LSB = 4
            MSB = 4
            MASK = 0x1
        class GreenLed:
            LSB = 5
            MSB = 5
            MASK = 0x1
        class BlueLed:
            LSB = 6
            MSB = 6
            MASK = 0x1
        class DebugPin0:
            LSB = 7
            MSB = 7
            MASK = 0x1
        class DebugPin1:
            LSB = 8
            MSB = 8
            MASK = 0x1
        class DebugPin2:
            LSB = 9
            MSB = 9
            MASK = 0x1
        class Reserved:
            LSB = 10
            MSB = 31
            MASK = 0x3fffff

        @staticmethod
        def unpack(reg_val: int) -> tuple[int, int, int, int, int, int, int, int, int, int, int]:
            f_rstn = (reg_val >> 0) & 0x1
            f_unlock_bitstream_section = (reg_val >> 1) & 0x1
            f_sw_led_enable = (reg_val >> 2) & 0x1
            f_sw_led = (reg_val >> 3) & 0x1
            f_red_led = (reg_val >> 4) & 0x1
            f_green_led = (reg_val >> 5) & 0x1
            f_blue_led = (reg_val >> 6) & 0x1
            f_debug_pin_0 = (reg_val >> 7) & 0x1
            f_debug_pin_1 = (reg_val >> 8) & 0x1
            f_debug_pin_2 = (reg_val >> 9) & 0x1
            f_reserved = (reg_val >> 10) & 0x3fffff
            return f_rstn, f_unlock_bitstream_section, f_sw_led_enable, f_sw_led, f_red_led, f_green_led, f_blue_led, f_debug_pin_0, f_debug_pin_1, f_debug_pin_2, f_reserved


        @staticmethod
        def pack(f_rstn: int, f_unlock_bitstream_section: int, f_sw_led_enable: int, f_sw_led: int, f_red_led: int, f_green_led: int, f_blue_led: int, f_debug_pin_0: int, f_debug_pin_1: int, f_debug_pin_2: int, f_reserved: int) -> int:
            reg_val = 0
            reg_val |= (f_rstn & 0x1) << 0
            reg_val |= (f_unlock_bitstream_section & 0x1) << 1
            reg_val |= (f_sw_led_enable & 0x1) << 2
            reg_val |= (f_sw_led & 0x1) << 3
            reg_val |= (f_red_led & 0x1) << 4
            reg_val |= (f_green_led & 0x1) << 5
            reg_val |= (f_blue_led & 0x1) << 6
            reg_val |= (f_debug_pin_0 & 0x1) << 7
            reg_val |= (f_debug_pin_1 & 0x1) << 8
            reg_val |= (f_debug_pin_2 & 0x1) << 9
            reg_val |= (f_reserved & 0x3fffff) << 10
            return reg_val
    class Status:
        ADDR = 0x1108000
        class Status:
            LSB = 0
            MSB = 31
            MASK = 0xffffffff

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_status = (reg_val >> 0) & 0xffffffff
            return f_status


        @staticmethod
        def pack(f_status: int) -> int:
            reg_val = 0
            reg_val |= (f_status & 0xffffffff) << 0
            return reg_val
    class SdConfig:
        ADDR = 0x110c000
        class ForceWriteCrcOk:
            LSB = 0
            MSB = 0
            MASK = 0x1
        class IgnoreWriteCrcError:
            LSB = 8
            MSB = 8
            MASK = 0x1
        class ConnectCrcErrorToInterrupt:
            LSB = 16
            MSB = 16
            MASK = 0x1
        class CrcError:
            LSB = 24
            MSB = 24
            MASK = 0x1

        @staticmethod
        def unpack(reg_val: int) -> tuple[int, int, int, int]:
            f_force_write_crc_ok = (reg_val >> 0) & 0x1
            f_ignore_write_crc_error = (reg_val >> 8) & 0x1
            f_connect_crc_error_to_interrupt = (reg_val >> 16) & 0x1
            f_crc_error = (reg_val >> 24) & 0x1
            return f_force_write_crc_ok, f_ignore_write_crc_error, f_connect_crc_error_to_interrupt, f_crc_error


        @staticmethod
        def pack(f_force_write_crc_ok: int, f_ignore_write_crc_error: int, f_connect_crc_error_to_interrupt: int, f_crc_error: int) -> int:
            reg_val = 0
            reg_val |= (f_force_write_crc_ok & 0x1) << 0
            reg_val |= (f_ignore_write_crc_error & 0x1) << 8
            reg_val |= (f_connect_crc_error_to_interrupt & 0x1) << 16
            reg_val |= (f_crc_error & 0x1) << 24
            return reg_val
    class BootAddress:
        ADDR = 0x1110000
        class Address:
            LSB = 0
            MSB = 31
            MASK = 0xffffffff

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_address = (reg_val >> 0) & 0xffffffff
            return f_address


        @staticmethod
        def pack(f_address: int) -> int:
            reg_val = 0
            reg_val |= (f_address & 0xffffffff) << 0
            return reg_val
