# Auto-generated by regmapper - DO NOT MODIFY
from enum import IntEnum


class DMAState(IntEnum):
    D_M_A_STATE_IDLE = 0
    D_M_A_STATE_BUSY = 1
    D_M_A_STATE_DONE = 2
    D_M_A_STATE_ERROR = 3


class DMAOpCode(IntEnum):
    D_M_A_OP_INVALID = 0
    D_M_A_OP_COPY = 1
    D_M_A_OP_WORD_SET = 2
    D_M_A_OP_BYTE_SET = 3

