# Auto-generated by regmapper - DO NOT MODIFY



class SpiFlash:
    BASE_ADDR = 0x0
    class Bitstream:
        BOTTOM_ENTRY = 0x0
        TOP_ENTRY = 0x1ffffc
        SIZE_BYTES = 0x200000
    class UserData:
        BOTTOM_ENTRY = 0x200000
        TOP_ENTRY = 0xfffffc
        SIZE_BYTES = 0xe00000
