# Auto-generated by regmapper - DO NOT MODIFY

from .spi_flash_regs import SpiFlash as _SpiFlash
from .csr_regs import Csr as _Csr
from .axil_pib_dma_regs import AxilPibDma as _AxilPibDma


class Top:
    BASE_ADDR = 0x0
    SpiFlash = _SpiFlash
    class Lram:
        BOTTOM_ENTRY = 0x1000000
        TOP_ENTRY = 0x104fffc
        SIZE_BYTES = 0x50000
    Csr = _Csr
    class IoBuff:
        BOTTOM_ENTRY = 0x1200000
        TOP_ENTRY = 0x120fffc
        SIZE_BYTES = 0x10000
    AxilPibDma = _AxilPibDma
