# Auto-generated by regmapper - DO NOT MODIFY



class AxilPibDma:
    BASE_ADDR = 0x20000000
    class IrqCtrl:
        ADDR = 0x20000000
        class Enable:
            LSB = 0
            MSB = 0
            MASK = 0x1

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_enable = (reg_val >> 0) & 0x1
            return f_enable


        @staticmethod
        def pack(f_enable: int) -> int:
            reg_val = 0
            reg_val |= (f_enable & 0x1) << 0
            return reg_val
    class Ack:
        ADDR = 0x20000004
        class Error:
            LSB = 0
            MSB = 0
            MASK = 0x1
        class Irq:
            LSB = 8
            MSB = 8
            MASK = 0x1

        @staticmethod
        def unpack(reg_val: int) -> tuple[int, int]:
            f_error = (reg_val >> 0) & 0x1
            f_irq = (reg_val >> 8) & 0x1
            return f_error, f_irq


        @staticmethod
        def pack(f_error: int, f_irq: int) -> int:
            reg_val = 0
            reg_val |= (f_error & 0x1) << 0
            reg_val |= (f_irq & 0x1) << 8
            return reg_val
    class Status:
        ADDR = 0x20000008
        class UnsupportedOp:
            LSB = 0
            MSB = 0
            MASK = 0x1
        class WriteError:
            LSB = 8
            MSB = 8
            MASK = 0x1
        class ReadError:
            LSB = 16
            MSB = 16
            MASK = 0x1
        class State:
            LSB = 24
            MSB = 25
            MASK = 0x3

        @staticmethod
        def unpack(reg_val: int) -> tuple[int, int, int, int]:
            f_unsupported_op = (reg_val >> 0) & 0x1
            f_write_error = (reg_val >> 8) & 0x1
            f_read_error = (reg_val >> 16) & 0x1
            f_state = (reg_val >> 24) & 0x3
            return f_unsupported_op, f_write_error, f_read_error, f_state


        @staticmethod
        def pack(f_unsupported_op: int, f_write_error: int, f_read_error: int, f_state: int) -> int:
            reg_val = 0
            reg_val |= (f_unsupported_op & 0x1) << 0
            reg_val |= (f_write_error & 0x1) << 8
            reg_val |= (f_read_error & 0x1) << 16
            reg_val |= (f_state & 0x3) << 24
            return reg_val
    class Source:
        ADDR = 0x2000000c
        class Pointer:
            LSB = 0
            MSB = 31
            MASK = 0xffffffff

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_pointer = (reg_val >> 0) & 0xffffffff
            return f_pointer


        @staticmethod
        def pack(f_pointer: int) -> int:
            reg_val = 0
            reg_val |= (f_pointer & 0xffffffff) << 0
            return reg_val
    class Length:
        ADDR = 0x20000010
        class Bytes:
            LSB = 0
            MSB = 31
            MASK = 0xffffffff

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_bytes = (reg_val >> 0) & 0xffffffff
            return f_bytes


        @staticmethod
        def pack(f_bytes: int) -> int:
            reg_val = 0
            reg_val |= (f_bytes & 0xffffffff) << 0
            return reg_val
    class Destination:
        ADDR = 0x20000014
        class Pointer:
            LSB = 0
            MSB = 31
            MASK = 0xffffffff

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_pointer = (reg_val >> 0) & 0xffffffff
            return f_pointer


        @staticmethod
        def pack(f_pointer: int) -> int:
            reg_val = 0
            reg_val |= (f_pointer & 0xffffffff) << 0
            return reg_val
    class Control:
        ADDR = 0x20000018
        class Op:
            LSB = 0
            MSB = 7
            MASK = 0xff

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_op = (reg_val >> 0) & 0xff
            return f_op


        @staticmethod
        def pack(f_op: int) -> int:
            reg_val = 0
            reg_val |= (f_op & 0xff) << 0
            return reg_val
    class Set:
        ADDR = 0x2000001c
        class Val:
            LSB = 0
            MSB = 31
            MASK = 0xffffffff

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_val = (reg_val >> 0) & 0xffffffff
            return f_val


        @staticmethod
        def pack(f_val: int) -> int:
            reg_val = 0
            reg_val |= (f_val & 0xffffffff) << 0
            return reg_val
