# Auto-generated by regmapper - DO NOT MODIFY



class Csr:
    BASE_ADDR = 0x10000000
    class Command:
        ADDR = 0x10000000
        class Command:
            LSB = 0
            MSB = 31
            MASK = 0xffffffff

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_command = (reg_val >> 0) & 0xffffffff
            return f_command


        @staticmethod
        def pack(f_command: int) -> int:
            reg_val = 0
            reg_val |= (f_command & 0xffffffff) << 0
            return reg_val
    class Config:
        ADDR = 0x10004000
        class Rstn:
            LSB = 0
            MSB = 0
            MASK = 0x1
        class UnlockBitstreamSection:
            LSB = 1
            MSB = 1
            MASK = 0x1
        class SwLedEnable:
            LSB = 2
            MSB = 2
            MASK = 0x1
        class SwLed:
            LSB = 3
            MSB = 3
            MASK = 0x1
        class GreenLed:
            LSB = 4
            MSB = 4
            MASK = 0x1
        class DebugPin0:
            LSB = 5
            MSB = 5
            MASK = 0x1
        class Reserved:
            LSB = 6
            MSB = 31
            MASK = 0x3ffffff

        @staticmethod
        def unpack(reg_val: int) -> tuple[int, int, int, int, int, int, int]:
            f_rstn = (reg_val >> 0) & 0x1
            f_unlock_bitstream_section = (reg_val >> 1) & 0x1
            f_sw_led_enable = (reg_val >> 2) & 0x1
            f_sw_led = (reg_val >> 3) & 0x1
            f_green_led = (reg_val >> 4) & 0x1
            f_debug_pin_0 = (reg_val >> 5) & 0x1
            f_reserved = (reg_val >> 6) & 0x3ffffff
            return f_rstn, f_unlock_bitstream_section, f_sw_led_enable, f_sw_led, f_green_led, f_debug_pin_0, f_reserved


        @staticmethod
        def pack(f_rstn: int, f_unlock_bitstream_section: int, f_sw_led_enable: int, f_sw_led: int, f_green_led: int, f_debug_pin_0: int, f_reserved: int) -> int:
            reg_val = 0
            reg_val |= (f_rstn & 0x1) << 0
            reg_val |= (f_unlock_bitstream_section & 0x1) << 1
            reg_val |= (f_sw_led_enable & 0x1) << 2
            reg_val |= (f_sw_led & 0x1) << 3
            reg_val |= (f_green_led & 0x1) << 4
            reg_val |= (f_debug_pin_0 & 0x1) << 5
            reg_val |= (f_reserved & 0x3ffffff) << 6
            return reg_val
    class Status:
        ADDR = 0x10008000
        class Status:
            LSB = 0
            MSB = 31
            MASK = 0xffffffff

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_status = (reg_val >> 0) & 0xffffffff
            return f_status


        @staticmethod
        def pack(f_status: int) -> int:
            reg_val = 0
            reg_val |= (f_status & 0xffffffff) << 0
            return reg_val
    class SdConfig:
        ADDR = 0x1000c000
        class ForceWriteCrcOk:
            LSB = 0
            MSB = 0
            MASK = 0x1
        class Reserved0:
            LSB = 1
            MSB = 7
            MASK = 0x7f
        class IgnoreWriteCrcError:
            LSB = 8
            MSB = 8
            MASK = 0x1
        class Reserved1:
            LSB = 9
            MSB = 15
            MASK = 0x7f
        class ConnectCrcErrorToInterrupt:
            LSB = 16
            MSB = 16
            MASK = 0x1
        class Reserved2:
            LSB = 17
            MSB = 23
            MASK = 0x7f
        class CrcError:
            LSB = 24
            MSB = 24
            MASK = 0x1
        class Reserved3:
            LSB = 25
            MSB = 31
            MASK = 0x7f

        @staticmethod
        def unpack(reg_val: int) -> tuple[int, int, int, int, int, int, int, int]:
            f_force_write_crc_ok = (reg_val >> 0) & 0x1
            f_reserved_0 = (reg_val >> 1) & 0x7f
            f_ignore_write_crc_error = (reg_val >> 8) & 0x1
            f_reserved_1 = (reg_val >> 9) & 0x7f
            f_connect_crc_error_to_interrupt = (reg_val >> 16) & 0x1
            f_reserved_2 = (reg_val >> 17) & 0x7f
            f_crc_error = (reg_val >> 24) & 0x1
            f_reserved_3 = (reg_val >> 25) & 0x7f
            return f_force_write_crc_ok, f_reserved_0, f_ignore_write_crc_error, f_reserved_1, f_connect_crc_error_to_interrupt, f_reserved_2, f_crc_error, f_reserved_3


        @staticmethod
        def pack(f_force_write_crc_ok: int, f_reserved_0: int, f_ignore_write_crc_error: int, f_reserved_1: int, f_connect_crc_error_to_interrupt: int, f_reserved_2: int, f_crc_error: int, f_reserved_3: int) -> int:
            reg_val = 0
            reg_val |= (f_force_write_crc_ok & 0x1) << 0
            reg_val |= (f_reserved_0 & 0x7f) << 1
            reg_val |= (f_ignore_write_crc_error & 0x1) << 8
            reg_val |= (f_reserved_1 & 0x7f) << 9
            reg_val |= (f_connect_crc_error_to_interrupt & 0x1) << 16
            reg_val |= (f_reserved_2 & 0x7f) << 17
            reg_val |= (f_crc_error & 0x1) << 24
            reg_val |= (f_reserved_3 & 0x7f) << 25
            return reg_val
    class TrapMcause:
        ADDR = 0x10010000
        class TrapMcause:
            LSB = 0
            MSB = 31
            MASK = 0xffffffff

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_trap_mcause = (reg_val >> 0) & 0xffffffff
            return f_trap_mcause


        @staticmethod
        def pack(f_trap_mcause: int) -> int:
            reg_val = 0
            reg_val |= (f_trap_mcause & 0xffffffff) << 0
            return reg_val
    class TrapMepc:
        ADDR = 0x10010004
        class TrapMepc:
            LSB = 0
            MSB = 31
            MASK = 0xffffffff

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_trap_mepc = (reg_val >> 0) & 0xffffffff
            return f_trap_mepc


        @staticmethod
        def pack(f_trap_mepc: int) -> int:
            reg_val = 0
            reg_val |= (f_trap_mepc & 0xffffffff) << 0
            return reg_val
    class TrapMtval:
        ADDR = 0x10010008
        class TrapMtval:
            LSB = 0
            MSB = 31
            MASK = 0xffffffff

        @staticmethod
        def unpack(reg_val: int) -> int:
            f_trap_mtval = (reg_val >> 0) & 0xffffffff
            return f_trap_mtval


        @staticmethod
        def pack(f_trap_mtval: int) -> int:
            reg_val = 0
            reg_val |= (f_trap_mtval & 0xffffffff) << 0
            return reg_val
