/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

#pragma once

typedef enum {
	kDMAStateIdle = 0,
	kDMAStateBusy = 1,
	kDMAStateDone = 2,
	kDMAStateError = 3
} DMAState;

typedef enum {
	kDMAOpInvalid = 0,
	kDMAOpCopy = 1,
	kDMAOpWordSet = 2,
	kDMAOpByteSet = 3
} DMAOpCode;
