/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

#include "axil_pib_dma_pack_unpack.h"

void
packAxilPibDmaIrqCtrl(
	uint32_t *	registerValue,
	bool *		enable)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*enable & 0x1) << 0;

	*registerValue = reg_val;
}

void
packAxilPibDmaAck(
	uint32_t *	registerValue,
	bool *		error,
	bool *		irq)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*error & 0x1) << 0;
	reg_val |= ((uint32_t)*irq & 0x1) << 8;

	*registerValue = reg_val;
}

void
unpackAxilPibDmaStatus(
	uint32_t *	registerValue,
	bool *		unsupported_op,
	bool *		write_error,
	bool *		read_error,
	DMAState *	state)
{
	uint32_t reg_val = *registerValue;
	*unsupported_op= (bool)((reg_val >> 0) & 0x1);
	*write_error= (bool)((reg_val >> 8) & 0x1);
	*read_error= (bool)((reg_val >> 16) & 0x1);
	*state= (DMAState)((reg_val >> 24) & 0x3);
}

void
packAxilPibDmaSource(
	uint32_t *	registerValue,
	uint32_t *	pointer)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*pointer & 0xffffffff) << 0;

	*registerValue = reg_val;
}

void
packAxilPibDmaLength(
	uint32_t *	registerValue,
	uint32_t *	bytes)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*bytes & 0xffffffff) << 0;

	*registerValue = reg_val;
}

void
packAxilPibDmaDestination(
	uint32_t *	registerValue,
	uint32_t *	pointer)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*pointer & 0xffffffff) << 0;

	*registerValue = reg_val;
}

void
packAxilPibDmaControl(
	uint32_t *	registerValue,
	DMAOpCode *	op)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*op & 0xff) << 0;

	*registerValue = reg_val;
}

void
packAxilPibDmaSet(
	uint32_t *	registerValue,
	uint32_t *	val)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*val & 0xffffffff) << 0;

	*registerValue = reg_val;
}
