/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include "axil_pib_dma_reg_types.h"

void
packAxilPibDmaIrqCtrl(
	uint32_t *	registerValue,
	bool *		enable
);

void
packAxilPibDmaAck(
	uint32_t *	registerValue,
	bool *		error,
	bool *		irq
);

void
unpackAxilPibDmaStatus(
	uint32_t *	registerValue,
	bool *		unsupported_op,
	bool *		write_error,
	bool *		read_error,
	DMAState *	state
);

void
packAxilPibDmaSource(
	uint32_t *	registerValue,
	uint32_t *	pointer
);

void
packAxilPibDmaLength(
	uint32_t *	registerValue,
	uint32_t *	bytes
);

void
packAxilPibDmaDestination(
	uint32_t *	registerValue,
	uint32_t *	pointer
);

void
packAxilPibDmaControl(
	uint32_t *	registerValue,
	DMAOpCode *	op
);

void
packAxilPibDmaSet(
	uint32_t *	registerValue,
	uint32_t *	val
);
