/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#pragma once

#include <stdint.h>
#include <stdbool.h>

void	unpackCsrCommand(
	uint32_t *	registerValue,
	uint32_t *	command
);
void	packCsrCommand(
	uint32_t *	registerValue,
	uint32_t *	command
);

void	unpackCsrConfig(
	uint32_t *	registerValue,
	bool *		rstn,
	bool *		unlock_bitstream_section,
	bool *		sw_led_enable,
	bool *		sw_led,
	bool *		red_led,
	bool *		green_led,
	bool *		blue_led,
	bool *		debug_pin_0,
	bool *		debug_pin_1,
	bool *		debug_pin_2,
	uint32_t *	reserved
);
void	packCsrConfig(
	uint32_t *	registerValue,
	bool *		rstn,
	bool *		unlock_bitstream_section,
	bool *		sw_led_enable,
	bool *		sw_led,
	bool *		red_led,
	bool *		green_led,
	bool *		blue_led,
	bool *		debug_pin_0,
	bool *		debug_pin_1,
	bool *		debug_pin_2,
	uint32_t *	reserved
);

void	unpackCsrStatus(
	uint32_t *	registerValue,
	uint32_t *	status
);
void	packCsrStatus(
	uint32_t *	registerValue,
	uint32_t *	status
);

void	unpackCsrSdConfig(
	uint32_t *	registerValue,
	bool *		force_write_crc_ok,
	bool *		ignore_write_crc_error,
	bool *		connect_crc_error_to_interrupt,
	bool *		crc_error
);
void	packCsrSdConfig(
	uint32_t *	registerValue,
	bool *		force_write_crc_ok,
	bool *		ignore_write_crc_error,
	bool *		connect_crc_error_to_interrupt,
	bool *		crc_error
);

void	unpackCsrBootAddress(
	uint32_t *	registerValue,
	uint32_t *	address
);
void	packCsrBootAddress(
	uint32_t *	registerValue,
	uint32_t *	address
);
