/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#pragma once

#include <stdint.h>
#include <stdbool.h>

void	getCsrCommand(
	uint32_t *	command
);
void	setCsrCommand(
	uint32_t *	command
);

void	getCsrConfig(
	bool *		rstn,
	bool *		unlock_bitstream_section,
	bool *		sw_led_enable,
	bool *		sw_led,
	bool *		red_led,
	bool *		green_led,
	bool *		blue_led,
	bool *		debug_pin_0,
	bool *		debug_pin_1,
	bool *		debug_pin_2,
	uint32_t *	reserved
);
void	setCsrConfig(
	bool *		rstn,
	bool *		unlock_bitstream_section,
	bool *		sw_led_enable,
	bool *		sw_led,
	bool *		red_led,
	bool *		green_led,
	bool *		blue_led,
	bool *		debug_pin_0,
	bool *		debug_pin_1,
	bool *		debug_pin_2,
	uint32_t *	reserved
);

void	getCsrStatus(
	uint32_t *	status
);
void	setCsrStatus(
	uint32_t *	status
);

void	getCsrSdConfig(
	bool *		force_write_crc_ok,
	bool *		ignore_write_crc_error,
	bool *		connect_crc_error_to_interrupt,
	bool *		crc_error
);
void	setCsrSdConfig(
	bool *		force_write_crc_ok,
	bool *		ignore_write_crc_error,
	bool *		connect_crc_error_to_interrupt,
	bool *		crc_error
);

void	getCsrBootAddress(
	uint32_t *	address
);
void	setCsrBootAddress(
	uint32_t *	address
);
