/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#pragma once

#include <stdint.h>
#include <stdbool.h>

void
unpackCsrCommand(
	uint32_t *	registerValue,
	uint32_t *	command
);
void
packCsrCommand(
	uint32_t *	registerValue,
	uint32_t *	command
);

void
unpackCsrConfig(
	uint32_t *	registerValue,
	bool *		rstn,
	bool *		sw_led_enable,
	bool *		sw_led,
	bool *		red_led,
	bool *		green_led,
	bool *		blue_led,
	bool *		debug_pin_0,
	bool *		debug_pin_1,
	bool *		debug_pin_2
);
void
packCsrConfig(
	uint32_t *	registerValue,
	bool *		rstn,
	bool *		sw_led_enable,
	bool *		sw_led,
	bool *		red_led,
	bool *		green_led,
	bool *		blue_led,
	bool *		debug_pin_0,
	bool *		debug_pin_1,
	bool *		debug_pin_2
);

void
unpackCsrStatus(
	uint32_t *	registerValue,
	uint32_t *	status
);
void
packCsrStatus(
	uint32_t *	registerValue,
	uint32_t *	status
);

void
unpackCsrSdConfig(
	uint32_t *	registerValue,
	bool *		force_write_crc_ok,
	bool *		ignore_write_crc_error,
	bool *		connect_crc_error_to_interrupt,
	bool *		crc_error
);
void
packCsrSdConfig(
	uint32_t *	registerValue,
	bool *		force_write_crc_ok,
	bool *		ignore_write_crc_error,
	bool *		connect_crc_error_to_interrupt,
	bool *		crc_error
);

void
unpackCsrTrapMcause(
	uint32_t *	registerValue,
	uint32_t *	trap_mcause
);
void
packCsrTrapMcause(
	uint32_t *	registerValue,
	uint32_t *	trap_mcause
);

void
unpackCsrTrapMepc(
	uint32_t *	registerValue,
	uint32_t *	trap_mepc
);
void
packCsrTrapMepc(
	uint32_t *	registerValue,
	uint32_t *	trap_mepc
);

void
unpackCsrTrapMtval(
	uint32_t *	registerValue,
	uint32_t *	trap_mtval
);
void
packCsrTrapMtval(
	uint32_t *	registerValue,
	uint32_t *	trap_mtval
);

void
unpackCsrBitstreamUnlock(
	uint32_t *	registerValue,
	uint32_t *	key
);
void
packCsrBitstreamUnlock(
	uint32_t *	registerValue,
	uint32_t *	key
);
