/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

#include "csr_regs.h"

void
getCsrCommand(
	uint32_t *	command)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x8200000);
	*command= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
setCsrCommand(
	uint32_t *	command)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*command & 0xffffffff) << 0;

	*(volatile uint32_t *)(0x8200000) = reg_val;
}

void
getCsrConfig(
	bool *		rstn,
	bool *		unlock_bitstream_section,
	bool *		sw_led_enable,
	bool *		sw_led,
	bool *		red_led,
	bool *		green_led,
	bool *		blue_led,
	bool *		debug_pin_0,
	bool *		debug_pin_1,
	bool *		debug_pin_2,
	uint32_t *	reserved)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x8204000);
	*rstn= (bool)((reg_val >> 0) & 0x1);
	*unlock_bitstream_section= (bool)((reg_val >> 1) & 0x1);
	*sw_led_enable= (bool)((reg_val >> 2) & 0x1);
	*sw_led= (bool)((reg_val >> 3) & 0x1);
	*red_led= (bool)((reg_val >> 4) & 0x1);
	*green_led= (bool)((reg_val >> 5) & 0x1);
	*blue_led= (bool)((reg_val >> 6) & 0x1);
	*debug_pin_0= (bool)((reg_val >> 7) & 0x1);
	*debug_pin_1= (bool)((reg_val >> 8) & 0x1);
	*debug_pin_2= (bool)((reg_val >> 9) & 0x1);
	*reserved= (uint32_t)((reg_val >> 10) & 0x3fffff);
}
void
setCsrConfig(
	bool *		rstn,
	bool *		unlock_bitstream_section,
	bool *		sw_led_enable,
	bool *		sw_led,
	bool *		red_led,
	bool *		green_led,
	bool *		blue_led,
	bool *		debug_pin_0,
	bool *		debug_pin_1,
	bool *		debug_pin_2,
	uint32_t *	reserved)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*rstn & 0x1) << 0;
	reg_val |= ((uint32_t)*unlock_bitstream_section & 0x1) << 1;
	reg_val |= ((uint32_t)*sw_led_enable & 0x1) << 2;
	reg_val |= ((uint32_t)*sw_led & 0x1) << 3;
	reg_val |= ((uint32_t)*red_led & 0x1) << 4;
	reg_val |= ((uint32_t)*green_led & 0x1) << 5;
	reg_val |= ((uint32_t)*blue_led & 0x1) << 6;
	reg_val |= ((uint32_t)*debug_pin_0 & 0x1) << 7;
	reg_val |= ((uint32_t)*debug_pin_1 & 0x1) << 8;
	reg_val |= ((uint32_t)*debug_pin_2 & 0x1) << 9;
	reg_val |= ((uint32_t)*reserved & 0x3fffff) << 10;

	*(volatile uint32_t *)(0x8204000) = reg_val;
}

void
getCsrStatus(
	uint32_t *	status)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x8208000);
	*status= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
setCsrStatus(
	uint32_t *	status)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*status & 0xffffffff) << 0;

	*(volatile uint32_t *)(0x8208000) = reg_val;
}

void
getCsrSdConfig(
	bool *		force_write_crc_ok,
	bool *		ignore_write_crc_error,
	bool *		connect_crc_error_to_interrupt,
	bool *		crc_error)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x820c000);
	*force_write_crc_ok= (bool)((reg_val >> 0) & 0x1);
	*ignore_write_crc_error= (bool)((reg_val >> 8) & 0x1);
	*connect_crc_error_to_interrupt= (bool)((reg_val >> 16) & 0x1);
	*crc_error= (bool)((reg_val >> 24) & 0x1);
}
void
setCsrSdConfig(
	bool *		force_write_crc_ok,
	bool *		ignore_write_crc_error,
	bool *		connect_crc_error_to_interrupt,
	bool *		crc_error)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*force_write_crc_ok & 0x1) << 0;
	reg_val |= ((uint32_t)*ignore_write_crc_error & 0x1) << 8;
	reg_val |= ((uint32_t)*connect_crc_error_to_interrupt & 0x1) << 16;
	reg_val |= ((uint32_t)*crc_error & 0x1) << 24;

	*(volatile uint32_t *)(0x820c000) = reg_val;
}

void
getCsrTrapMcause(
	uint32_t *	trap_mcause)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x8210000);
	*trap_mcause= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
setCsrTrapMcause(
	uint32_t *	trap_mcause)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*trap_mcause & 0xffffffff) << 0;

	*(volatile uint32_t *)(0x8210000) = reg_val;
}

void
getCsrTrapMepc(
	uint32_t *	trap_mepc)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x8210004);
	*trap_mepc= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
setCsrTrapMepc(
	uint32_t *	trap_mepc)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*trap_mepc & 0xffffffff) << 0;

	*(volatile uint32_t *)(0x8210004) = reg_val;
}

void
getCsrTrapMtval(
	uint32_t *	trap_mtval)
{
	uint32_t reg_val = *(volatile uint32_t *)(0x8210008);
	*trap_mtval= (uint32_t)((reg_val >> 0) & 0xffffffff);
}
void
setCsrTrapMtval(
	uint32_t *	trap_mtval)
{
	uint32_t reg_val = 0;
	reg_val |= ((uint32_t)*trap_mtval & 0xffffffff) << 0;

	*(volatile uint32_t *)(0x8210008) = reg_val;
}
