/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#define TopFlashOtpTopEntry (0x80001fc)
#define TopFlashOtpBottomEntry (0x8000000)
#define TopLramTopEntry (0x814fffc)
#define TopLramBottomEntry (0x8100000)
#define TopIoBuffTopEntry (0x830fffc)
#define TopIoBuffBottomEntry (0x8300000)

/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#define SpiFlashBitstreamTopEntry (0x1ffffc)
#define SpiFlashBitstreamBottomEntry (0x0)
#define SpiFlashUserDataTopEntry (0xfffffc)
#define SpiFlashUserDataBottomEntry (0x200000)

/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */

