/*
 *	Autogenerated by regmapper - DO NOT MODIFY
 */
#pragma once

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>


uint32_t	getSpiFlashBitstreamEntry(size_t offset);

void	setSpiFlashBitstreamEntry(size_t offset, uint32_t *  value);


uint32_t	getSpiFlashUserDataEntry(size_t offset);

void	setSpiFlashUserDataEntry(size_t offset, uint32_t *  value);
